### ISSUE TITLE
7.0.0 RC1 Could not find daterangepicker.css for the bundle LeptonXLite.Global

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#14701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

7.0.0 RC1 can't open login page successfully, could not find `daterangepicker.css`.

### Reproduction Steps

- PowerShell

`abp new TestProject --ui none -csf --preview`

- Action

Open Swagger and Click the authorize button, then redirect to the login url will get an error.

### Expected behavior

Open the login page without an error.

### Actual behavior

- Exception: 

Could not find the bundle file '/libs/bootstrap-daterangepicker/daterangepicker.css' for the bundle 'LeptonXLite.Global'!

### Regression?

6.0.1 is fine.

### Version

7.0.0-rc1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

User Interface: None

**Comment by maliming** [comment]
It was fixed in rc2 and we will release it soon.

**Comment by xorinzor** [comment]
@maliming what steps should be followed after upgrading? This issue still occurs for me after updating everything to the latest version (7.0.3). Tried updating the npm and yarn packages too, no change.
