### ISSUE TITLE
Blazorise DataGrid actions dropdown overflow issue

### ISSUE THREAD

**Issue by Jawad-Chughtai** [abpframework/abp#19859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using Blazor Server with LeptonX theme and when actions dropdown is clicked inside the DataGrid that is "Responsive=true", the overflow of Dropdown menu is hidden and applying z-index to this dropdown menu does not seem to work.
![image](https://github.com/abpframework/abp/assets/95006558/12ab9bba-e70d-4b82-bb47-4daf9c0c5f87)

### Reproduction Steps

Creating a new Project with Blazor Server and .Net 8.
Following the ABP.io tutorial for Blazor Server for creating CRUD page.
Set DataGrid to Responsive=true, and make sure of enough columns for scrollbar to be visible.
Add 6-7 menu items in Actions dropdown in the datagrid.
Add only one or a couple of records so that, the dropdown opens towards top.

### Expected behavior

The dropdown should be fully visible above the datagrid, and overflow should not be hidden
![image](https://github.com/abpframework/abp/assets/95006558/de208311-9711-4c4f-acdb-9a678b55208e)

### Actual behavior

When dropdown does not have enough space towards top, it's overflow is hidden
![image](https://github.com/abpframework/abp/assets/95006558/fcc5c62f-8554-45dc-834c-ac13fb138dfe)

### Version

8.0.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
The problem has been solved. You can try the latest version.

<img width="479" alt="image" src="https://github.com/abpframework/abp/assets/16813853/785616c5-9af8-46bf-8457-dd98fe74897a">

And please open a ticket on the support website if it's a bug. thanks for understanding

**Comment by Jawad-Chughtai** [comment]
Hello @realLiangshiwei. For me updating the project to latest version using abp update does not resolve this problem. I do not own a license so can I still create a ticket for bug on support? 
![image](https://github.com/abpframework/abp/assets/95006558/4951a3a4-e406-4c18-9d96-50d59d048860)

**Comment by realLiangshiwei** [comment]
You can report it here: https://support.abp.io/QA/Questions/6711/Bugs--Issues-v81x

**Comment by realLiangshiwei** [comment]
Are you using the Leptonx lite theme?

**Comment by Jawad-Chughtai** [comment]
@realLiangshiwei Yes
![image](https://github.com/abpframework/abp/assets/95006558/b83d2653-48ca-4038-accb-cebf5cee8453)

**Comment by realLiangshiwei** [comment]
I will fix it, you can add those styles to your CSS
```
.table-responsive {
  min-height: 580px;
  margin-bottom: 1rem;
}
```

**Comment by Jawad-Chughtai** [comment]
@realLiangshiwei Thank you
