### ISSUE TITLE
unable to login using abp-cli

### ISSUE THREAD

**Issue by dotnicht** [abpframework/abp#20427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

error message: There is no entity OpenIddictApplication with id = 3a095c7d-08f6-e447-6484-b4ddc659e6bb!

### Version

8.2.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Linux

**Comment by xlcommunities** [comment]
I'm also seeing this same issue.

**Comment by salihozkara** [comment]
This issue has been resolved, can you check again? @dotnicht @xlcommunities

**Comment by gdlcf88** [comment]
Hi, @salihozkara. I think the bug is still there.
<img width="974" alt="image" src="https://github.com/user-attachments/assets/d08aba53-6ab1-425c-a7c0-64260f2424ff">

**Comment by salihozkara** [comment]
> Hi, @salihozkara. I think the bug is still there. <img alt="image" width="974" src="https://private-user-images.githubusercontent.com/30018771/355786261-d08aba53-6ab1-425c-a7c0-64260f2424ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzAxNTksIm5iZiI6MTcyMzAyOTg1OSwicGF0aCI6Ii8zMDAxODc3MS8zNTU3ODYyNjEtZDA4YWJhNTMtNmFiMS00MjVjLWE3YzAtNjQyNjBmMjQyNGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDExMjQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYjA3NWQ5YjczYjlhNDFhMzM4MWE4MmU5YWNlZjkwNzBkZTI2NTg4YzY1NTNjMDI5MDg0OWRlZjM0ODMyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFlBaH6aeBwBwrxU0gkRwcwQkjxJBz58vuJ_DC2ypYc">

This issue has been resolved, can you check again?
