### ISSUE TITLE
Angular error TS2304: Cannot find name 'provideSideMenuLayout'.

### ISSUE THREAD

**Issue by JanaElnagar** [abpframework/abp#24388]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Upon creating a new abp multi-layer project with angular ui, running ng serve gives the error:
```
Error: src/app/app.config.ts:28:5 - error TS2304: Cannot find name 'provideSideMenuLayout'.

28     provideSideMenuLayout(),
       ~~~~~~~~~~~~~~~~~~~~~
```
I'm using angular version 20.3.13, abp 9.3.5, .NET sdk 9.0.305

### Reproduction Steps

`abp new Acme.Bookstore -u angular -csf --version 9.3.5`

`cd Acme.Bookstore/angular`

`ng serve`

### Version

9.3.5

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by erdemcaygor** [comment]
Hello, I've created a new project using your example command and it appears to work correctly on my end. Could you please delete the `node_modules` and `yarn.lock` files in the angular folder and reinstall the dependencies using the `yarn` command? The issue may have occurred during the initial package installation when the project was generated.

**Comment by JanaElnagar** [comment]
hello, ok but I dont have `yarn` and I've been using `npm install` instead, it also shows errors, do I need to use yarn instead of npm? 

<img width="1116" height="509" alt="Image" src="https://github.com/user-attachments/assets/771dd0fc-b451-4708-b581-d79e548b9407" />

npm version `10.9.3`

**Comment by JanaElnagar** [comment]
I've installed yarn and ran the command, the packages were installed however `ng serve` now shows this error

<img width="1507" height="61" alt="Image" src="https://github.com/user-attachments/assets/8178be49-7596-4c15-b083-4c9d3420c120" />

logs:
```
[error] file:///C:/Users/jana.elnagar/source/repos/Acme.Bookstore/angular/node_modules/@angular/compiler-cli/bundles/chunk-YDQJH54W.js:20094
import { BindingPipe as BindingPipe3, CombinedRecursiveAstVisitor, tmplAstVisitAll, BindingPipeType } from "@angular/compiler";
                                                                                    ^^^^^^^^^^^^^^^
SyntaxError: The requested module '@angular/compiler' does not provide an export named 'BindingPipeType'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:228:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ModuleJob.run (node:internal/modules/esm/module_job:337:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async readTsconfig (C:\Users\jana.elnagar\source\repos\Acme.Bookstore\angular\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:58:54)
    at async configureI18nBuild (C:\Users\jana.elnagar\source\repos\Acme.Bookstore\angular\node_modules\@angular-devkit\build-angular\src\utils\i18n-webpack.js:31:22)
    at async generateI18nBrowserWebpackConfigFromContext (C:\Users\jana.elnagar\source\repos\Acme.Bookstore\angular\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:79:36)
    at async setup (C:\Users\jana.elnagar\source\repos\Acme.Bookstore\angular\node_modules\@angular-devkit\build-angular\src\builders\dev-server\webpack-server.js:107:34)

```

**Comment by JanaElnagar** [comment]
I tried now creating a new project from scratch and using `yarn` first, `ng serve` still shows the same initial error

```
Error: src/app/app.config.ts:28:5 - error TS2304: Cannot find name 'provideSideMenuLayout'.

28     provideSideMenuLayout(),
       ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by erdemcaygor** [comment]
Hello, I was able to reproduce the error when using npm. Could you please remove the `node_modules` folder and `package-lock.json` file, then reinstall the packages with `npm install --legacy-peer-deps`? This should resolve the issue. However, I couldn't reproduce this issue with yarn

**Comment by JanaElnagar** [comment]
I tried `npm install --legacy-peer-deps` and it fixed the package downloading errors, however there is still the same ` Error: src/app/app.config.ts:28:5 - error TS2304: Cannot find name 'provideSideMenuLayout'.` error when running `ng serve`

full error list when running `ng serve` after `npm install --legacy-peer-deps`:
```

./node_modules/@abp/ng.core/fesm2022/abp-ng.core-locale.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@abp\ng.core\fesm2022'

./node_modules/@abp/ng.core/fesm2022/abp-ng.core.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@abp\ng.core\fesm2022'

./node_modules/@abp/ng.oauth/fesm2022/abp-ng.oauth.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@abp\ng.oauth\fesm2022'

./node_modules/@angular/common/fesm2022/common.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@angular\common\fesm2022'

./node_modules/@angular/common/fesm2022/module.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@angular\common\fesm2022'

./node_modules/@angular/core/fesm2022/debug_node.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@angular\core\fesm2022'

./node_modules/@angular/core/fesm2022/resource.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@angular\core\fesm2022'

./node_modules/@angular/router/fesm2022/router_module.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@angular\router\fesm2022'

./node_modules/@volo/ngx-lepton-x.core/fesm2022/volo-ngx-lepton-x.core.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\@volo\ngx-lepton-x.core\fesm2022'

./node_modules/angular-oauth2-oidc/fesm2022/angular-oauth2-oidc.mjs:1:0-194 - Error: Module not found: Error: Can't resolve 'C:/Users/jana.elnagar/source/repos/Acme.Bookstore2/angular/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'C:\Users\jana.elnagar\source\repos\Acme.Bookstore2\angular\node_modules\angular-oauth2-oidc\fesm2022'

Error: src/app/app.config.ts:28:5 - error TS2304: Cannot find name 'provideSideMenuLayout'.

28     provideSideMenuLayout(),
       ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by erdemcaygor** [comment]
Could you please share your package.json file?

**Comment by JanaElnagar** [comment]
[package.json](https://github.com/user-attachments/files/24079899/package.json)

**Comment by erdemcaygor** [comment]
Hello, I was able to reproduce the error. To fix this issue, please follow these steps:

- Remove `node_modules`,` yarn.lock`, and `package-lock.json`
- Reinstall the dependencies using Yarn: `yarn install`
- Add the missing import to `app.config.ts`;

`
import { provideSideMenuLayout } from '@abp/ng.theme.lepton-x/layouts';
`

**Comment by JanaElnagar** [comment]
yes it worked, thanks a lot
