### ISSUE TITLE
abp generate-proxy does not create the model properties as set by the [JsonProperty] attribue

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#7776]
* **ABP Framework version** 4.2.1 (Stable).
* **User Interface** Angular.
* **Database Provider** EF Core 5

I'm using [vivet/GoogleApi](https://github.com/vivet/GoogleApi).
When `abp generate-proxy` generates a TypeScript model of a Dto that has a `[JsonProperty]` attribute; the output model has the name of the C# `property` instead of the name in the `attribute`.

For example, I'm returning: https://github.com/vivet/GoogleApi/blob/bed8a7988feba69bb9037afd597dc08b0a42195e/GoogleApi/Entities/Places/Details/Response/DetailsResult.cs#L23
![image](https://user-images.githubusercontent.com/2285974/108402622-7445fe80-7226-11eb-9096-f52042450923.png)

And what I'm getting in the generated model is:
![image](https://user-images.githubusercontent.com/2285974/108402746-98094480-7226-11eb-8078-6b916cebb721.png)

But the serializer in the `ApplicationService` is serializing it into the name put in the attribute:
![image](https://user-images.githubusercontent.com/2285974/108403416-5b8a1880-7227-11eb-81e7-f588ac0b1f6c.png)

Is there an option to overcome this problem, or am I missing something?

**Comment by cotur** [comment]
Hi @idreeshaddad,

We will investigate the issue and reply you asap. Thanks.

**Comment by idreeshaddad** [comment]
@cotur I hope you do it fast brother as we have a release soon.
Salams from your Chechen brothers here 😃

**Comment by hikalkan** [comment]
Resolved by #7819

Angular part has been moved to #7852

**Comment by idreeshaddad** [comment]
Thank you guys for the effort, but unfortunately the problem still exists after updating to 4.3:
![image](https://user-images.githubusercontent.com/2285974/116780929-45e76980-aa88-11eb-9d54-a59dc8c48214.png)


As you can see, abp generate-proxy generated a TypeScript model of a Dto that has a [JsonProperty] attribute; the output model has the name of the C# property instead of the name in the attribute!

(JsonProperty)
![image](https://user-images.githubusercontent.com/2285974/116781049-1b49e080-aa89-11eb-8920-1c1fcc5a3565.png)

(Abp generated TypeScript model)
![image](https://user-images.githubusercontent.com/2285974/116781018-e2117080-aa88-11eb-9553-7d0432e61b25.png)

**Comment by maliming** [comment]
@idreeshaddad 
Can you try a new project?

**Comment by armanozak** [comment]
Hi @idreeshaddad,

There is a package called `@abp/ng.schematics` in the package.json file. Please upgrade it to v4.3.0 and try again.

**Comment by idreeshaddad** [comment]
> Hi @idreeshaddad,
> 
> There is a package called `@abp/ng.schematics` in the package.json file. Please upgrade it to v4.3.0 and try again.

Thank you @armanozak it worked.
And for those who might stumble upon this issue: **Do not forget to npm install after you change the schematics version**, then abp generate-proxy , and enjoy programming.
