### ISSUE TITLE
bad performance Isgranted with redis

### ISSUE THREAD

**Issue by cem1835** [abpframework/abp#7788]
Hello,

My application has 500+ Permission Policy and  when I use redis, the average page load speed increasing by 50 seconds. (I don't use local redis).

I have attached the log files

I think you can change the caching mechanism on permissions (like ambient context
[logs-20210221.txt](https://github.com/abpframework/abp/files/6016469/logs-20210221.txt)

Thank you

**Comment by leonkosak** [comment]
[Related](https://github.com/abpframework/abp/issues/6115)?

**Comment by maliming** [comment]
Resolved by https://github.com/abpframework/abp/pull/7799

**Comment by cem1835** [comment]
problem still going on when loading the /Abp/ApplicationConfigurationScript

i found this while searching for the problem

https://github.com/abpframework/abp/blob/cfc648bc656da21b73d99578d71d0ac71b56b9c4/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationAppService.cs#L144

it loads all the cache one by one

**Comment by maliming** [comment]
hi

It checks the permissions one time.

https://github.com/abpframework/abp/blob/cfc648bc656da21b73d99578d71d0ac71b56b9c4/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationAppService.cs#L173

**Comment by cem1835** [comment]
permissionchecker performance 47 sec 
![image](https://user-images.githubusercontent.com/17495243/129871657-b93f63ff-ad94-4121-a0ac-315b119620e1.png)

**Comment by maliming** [comment]
You can further debug or use tools to check the problematic code that affects performance.

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionStore.cs#L137
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionStore.cs#L139
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Caching.StackExchangeRedis/Volo/Abp/Caching/StackExchangeRedis/AbpRedisCache.cs#L110
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Caching.StackExchangeRedis/Volo/Abp/Caching/StackExchangeRedis/AbpRedisCache.cs#L195
