### ISSUE TITLE
Closing a modal removes `modal-open` class from the `body` even when another modal is still open

### ISSUE THREAD

**Issue by gregbrant2** [abpframework/abp#8110]
* Your **ABP Framework version**: 4.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Angular UI
* Your database provider(EF Core/MongoDB): EF Core
* Exception message and **stack trace** if available (check the logs). N/A
* Steps needed to **reproduce** the problem.

If you create two modals within a component and open the 2nd one while the 1st is open, closing the 2nd one removes the `modal-open` class from the `<body>` tag and breaks the scroll behaviour of the remaining modal.

You'll need to make the content of the modals long enough to trigger scroll bars on your resolution.

I'll find some time later to put a repro together.

**Comment by maliming** [comment]
Waiting for your repro. : )

**Comment by gregbrant2** [comment]
@maliming  here you go.

https://github.com/gregbrant2/abp-nested-modals/tree/master

**Comment by mehmet-erim** [comment]
Hi @gregbrant2

There were known issues with abp-modal. So we fixed the problems and changed the working method a little bit. You can see the PR:
https://github.com/abpframework/abp/pull/7481

Will be available in v4.3

**Comment by gregbrant2** [comment]
Upgrading to 4.3 has not fixed this, in fact, it's now broken in a different way.

I've upgraded the repro to 4.3: 
https://github.com/gregbrant2/abp-nested-modals/tree/master

Now if you checkout and run that solution, clicking "Open Modal" in ABP Modal card shows the modal, but there is no `modal-open` class added to the body, so you can't scroll that modal.  Clicking the "Open Inner Modal" button does add the `modal-open` and you can scroll that second modal.  Closing that modal removes the `modal-open` class again, and you can't scroll the outer modal.

**Comment by gregbrant2** [comment]
@mehmet-erim would it be able to get an update on this. There are still issues with having multiple modals open.

**Comment by mehmet-erim** [comment]
Hi @gregbrant2,

We will work on this. It'll probably be fixed in v4.3.1.

Thanks!

**Comment by jortygu** [comment]
this issue is still not fixed in v4.4.2.wo need to hardcode below to fixed this issue.
``` JavaScript
_secondModal.onClose(function (obj, evnt) {
    $(document.body).addClass("modal-open");
});
```
