### ISSUE TITLE
Design issue with EF repositories and autoSave = false

### ISSUE THREAD

**Issue by scott7106** [abpframework/abp#8740]
* ABP v4.2.2
* Angular
* EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

The issue below is a design issue and (maybe) a bug. It can be seen in the Angular client or in the API itself using PostMan since the problem is between the repository and the app service. As a note, prior to Dec 2020, I am pretty sure this worked as expected in our application.

In my AppService, I am calling UpdateAsync for the associated repository (see code snippet below). Note that I am not setting the optional parameter for autoSave which means it is defaulting to false.
```
    modelTable = await _modelTableRepository.UpdateAsync(modelTable);
    return ObjectMapper.Map<ModelTable, ModelTableDto>(modelTable);
```

The issue arises when the call to the database fails for any reason and you do not specify autoSave or you set it to false. In my case today, it was a unique constraint violation which caused the record to fail when written.  When autoSave is set to false, the call to DbContext.SaveChangesAsync for the update is not called until after the process exits the AppService method. The result is that the AppService reports a successful update operation to the user, when in fact, the operation did not succeed. The logs show the error, but that does not help the end user who mistakenly thinks his update was saved.

I can get the behavior I want by passing in the autoSave parameter with a value of true. However, I would argue the design choice of an operation which incorrectly reports a successful operation. I cannot think of any example where it is acceptable to report a successful update operation which failed to be persisted to the underlying data store.

**Comment by maliming** [comment]
> The result is that the AppService reports a successful update operation to the user, when in fact, the operation did not succeed. The logs show the error, but that does not help the end user who mistakenly thinks his update was saved.

Steps needed to reproduce the problem.

**Comment by scott7106** [comment]
Would it be possible to privately send a sample project demonstrating the issue? That would be much easier than explaining the steps. I have reproduced this with a simple example project I generated using ABP Suite.

**Comment by ebicoglu** [comment]
in your usage you must set `autoSave:true `
set autosave false when you have several queries and you don't want to make several db cycles.

**Comment by scott7106** [comment]
@ebicoglu while changing this setting produces a correct result, it is not the solution to the issue. There is a transaction scope problem with the repository code. There is never a situation where it is appropriate to report a successful change operation to the user which did not happen. By definition, this is a design flaw. The default setting for Update and Insert is autoSave = false which is optimistically assuming the write to the repository happened. When it doesn't, the application reports a success to the user and writes an error to the log message.

**Comment by maliming** [comment]
hi @scott7106  

You can send the project to liming.ma#volosoft.com

**Comment by scott7106** [comment]
hi @maliming 
The sample project was sent to your email along with instructions to reproduce the issue with the sample

**Comment by maliming** [comment]
hi @scott7106 

I think it will works when you removed `app.UseUnitOfWork();`.

We may not be able to handle the exception of the middleware in the middleware.

**Comment by maliming** [comment]
@hikalkan 

If we do not submit the unit of work in the MVC pipeline, the HTTP response will be written, which means that the exception in **AbpUnitOfWorkMiddleware** can't be handled. (`Response.HasStarted = true`)

The API returns success JSON and **HTTP OK code**, but the operation is not successful, and there will be exceptions in the log.

**Comment by hikalkan** [comment]
Interesting case. As understand, we can't properly handle error and send back to the client in UOW middleware since the response has already started. Yes, we accept that this is a problem that we should solve in the framework. 

One quick solution can be c ompleting the UOW in action/page filters. In the UOW middleware, we just do nothing if UOW is already completed. However, this can be a problem if UOW middleware is not used just on top of the MVC middleware.

However, it would better to understand first why Response.HasStarted = true. In this case, how a middleware can return an error even the next middleware success. @maliming can you try to understand this and find if there is a way to change MVC's behavior.

I am adding this for 4.3.1 release.

**Comment by maliming** [comment]
> it would better to understand first why Response.HasStarted = true. 

The return value will be written to the **Response** when the MVC action is executed. For example, set the status code, writing JSON, redirect to URL, etc.

Microsoft also checks the `HasStarted`. No more attempts to change anything if it's `true`.

we have to use uow in action/page filters to prevent `Response.HasStarted`

**Comment by hikalkan** [comment]
So, we should drop UOW middleware?

**Comment by maliming** [comment]
Yes.

**Comment by hikalkan** [comment]
I will think on this in the next days, because that's an important change.

**Comment by hikalkan** [comment]
@scott7106 for now, just remove `app.UseUnitOfWork()` from the ASP.NET Core pipeline, your problem should be solved.

**Comment by scott7106** [comment]
@hikalkan we opted for a different _intermediate_ solution

1. In cases where we were applying a single change to the database, we added autoSave = true. This was simple and does not have a major impact on the application.

2. In cases where we were applying several changes which we wanted wrapped in a UOW, we added the following statement to the end of the application service. We have verified this resolves our issues in all cases.
`await UnitOfWorkManager.Current.SaveChangesAsync();`

In the short term, this will work but it requires our developers to remember to call save for the unit of work before exiting the method in the AppService. This is not a clean design.

**Comment by AelithBlanchett** [comment]
Removing the .UseUnitOfWork(); call doesn't fix the problem completely as it still creates UoW in the background given that there are still interceptors creating other instances.
- When UnitOfWork Attribute is explicitly specified with IsDisabled (I also get a disposed error when I call a repository method in a service): https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs#L20
- When it isn't specified: https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Uow/AbpUowActionFilter.cs#L14

There are workarounds though:
- Not changing the properties data in any service call, even GET ones.
- Use AsNoTracking() when calling a repository method to make sure nothing gets saved to the database.

**Comment by scott7106** [comment]
Has there been any progress on this issue?

**Comment by hikalkan** [comment]
@scott7106 see https://github.com/abpframework/abp/issues/10568#issue-1048233070
